- name: conditions
  hosts: web
  become: yes
  tasks:
  - name: check user exists or not
    ansible.builtin.command: id expense
    ignore_errors: true
    register: USER
    ignore_error: true
  
  - name: print user information
    ansible.buitin.debug:
      msg: "user info: {{USER}}"

  - name: say hello
    ansible.builtin.debug:
      msg: "Hello"

  