- name: install and run nginx
  hosts: web
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.dnf:
    name: nginx
    state: latest

  - name: run nginx 
    ansible.bulitin.service:
    name: nginx
    state: started
    enabled: yes

