- name: variables
  hosts: localhost
  vars: 
    course: "ansible"
    Trainer: "siva"
    Duration: "120hrs"
  tasks:
  - name: print information
    ansible.builtin.debug:
     msg: "Hi, we are learning ansible, from trainer siva, duration is 120hrs"